# Generated by Django 4.2.1 on 2023-05-06 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipoarma', models.CharField(max_length=50)),
                ('calibre', models.CharField(max_length=10)),
                ('n_serie', models.CharField(max_length=50, unique=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Arma',
                'verbose_name_plural': 'Armas',
            },
        ),
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=15)),
                ('capacidade_pessoas', models.DecimalField(decimal_places=1, max_digits=2)),
                ('viatura', models.BooleanField(default=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Carro',
                'verbose_name_plural': 'Carros',
            },
        ),
        migrations.CreateModel(
            name='CompartilhamentoCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.carro')),
            ],
            options={
                'verbose_name': 'Compartilhamento de Carro',
                'verbose_name_plural': 'Compartilhamento de Carros',
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_patrimonio', models.CharField(max_length=50, unique=True)),
                ('marca', models.CharField(max_length=20)),
                ('processador', models.CharField(max_length=20)),
                ('tipo_ram', models.CharField(max_length=20)),
                ('qtd_ram', models.DecimalField(decimal_places=1, max_digits=2)),
                ('tip_per_armazenamento', models.CharField(max_length=3)),
                ('qtd_memoria', models.DecimalField(decimal_places=1, max_digits=2)),
                ('so', models.CharField(max_length=20)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('cpf', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('policial', models.BooleanField(default=False)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('arma', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.arma')),
                ('carros', models.ManyToManyField(blank=True, through='inventario.CompartilhamentoCarro', to='inventario.carro')),
                ('computador', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.computador')),
            ],
            options={
                'verbose_name': 'Pessoa',
                'verbose_name_plural': 'Pessoas',
            },
        ),
        migrations.CreateModel(
            name='RegistroArmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_registro', models.CharField(max_length=50, unique=True)),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao', to='inventario.arma')),
            ],
            options={
                'verbose_name': 'Resgistro Arma',
                'verbose_name_plural': 'Resgistro Armas',
            },
        ),
        migrations.AddField(
            model_name='compartilhamentocarro',
            name='pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carro_pessoa', to='inventario.pessoa'),
        ),
        migrations.CreateModel(
            name='PossePessoaObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateTimeField(auto_now_add=True)),
                ('atualizacao', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
                ('arma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.arma')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.carro')),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.computador')),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_posse', to='inventario.pessoa')),
            ],
            options={
                'verbose_name': 'Pessoa posse Objeto',
                'verbose_name_plural': 'Pessoas posse Objeto',
                'unique_together': {('computador', 'pessoa')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='compartilhamentocarro',
            unique_together={('carro', 'pessoa')},
        ),
    ]
