# Generated by Django 4.2.1 on 2023-05-08 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0005_pessoa_user_delete_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='password',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
