# Generated by Django 4.2.1 on 2023-05-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0006_pessoa_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='user',
        ),
    ]
